<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Tue Nov 27 2018 07:11:00 GMT+0000 (UTC)). */
return array(
	'es6-shim' => '0.35.3',
	'es7-shim' => '6.0.0',
	'i18n-react' => '0.6.4',
	'mobx' => '4.5.1',
	'mobx-state-tree' => '3.5.0',
	'react' => '16.5.2',
	'react-aiot' => '1.2.18',
	'react-dom' => '16.5.2'
);
