<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Tue Nov 27 2018 07:11:00 GMT+0000 (UTC)). */
return array(
	'public/dist/rml_shortcode.js' => 'd5afc3160e100b1e0d3ccf325c0b3075',
	'public/dist/rml.js' => 'c81e1ea180a0357b3827a7b01156d65b',
	'public/dist/rml.css' => '81b7863be91472e39139ace2deb68977',
	'public/dev/rml_shortcode.js' => 'bfde22476335e10064819599c5c4bd8e',
	'public/dev/rml.js' => 'd79ccfc7822d76f527260ed85aeeaee5',
	'public/dev/rml_shortcode.css' => '9a7cac4970a885476f97fd937b689eff',
	'public/dev/rml.css' => '92c0a229a762bd494db6bd87ddfb4561',
);
